### PR TITLE
ISSUE-408 fixed failing tests in role_mapping_blackbox_test, fixed cl…

### LINKED ISSUE #408: Fix cleanup of db records during role_mapping_blackbox_test
Tests are failing when the test suite is run a subsequent time because stray records are being left in the database by the `TestOKToSave()` test in `/authorization/role/repository/role_mapping_blackbox_test.go`

### PR DESCRIPTION
**Pull request by sbryzak**
Fixes #408 

Just a small PR, this fixes the problems when running subsequent iterations of `role_mapping_blackbox_test.go`.  The problem was due to an issue with the automatic db cleanup routine, which attempts to delete all records created during testing.  A referential integrity issue was introduced when the `TestOKToSave` test updated a role_mapping entity to point to a resource created after the role_mapping was created.  Fixed by changing the create order so that the resource is created first.

Another issue was identified in `controller/resource_blackbox_test.go` - The `TestUpdateResource` test was likewise updating a resource with a reference to a parent resource, thereby preventing it from being deleted also due to a constraint violation.  Fixed by adding another test where the child resource is updated yet again to clear the parent resource (this required fixing the resource controller also, as this feature wasn't previously supported).

### CODE REVIEW

File: authorization/role/repository/role_mapping_blackbox_test.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ func (s *roleMappingBlackBoxTest) createTestRoleMapping(fromResourceTypeName str
 }
 
 func (s *roleMappingBlackBoxTest) TestOKToLoad() {
-	rm1, err := s.createTestRoleMapping(authorization.IdentityResourceTypeOrganization, "employee", authorization.IdentityResourceTypeTeam, "member")
+	rm1, err := s.createTestRoleMapping(authorization.IdentityResourceTypeOrganization, "role_mapping_test_role_personnel", authorization.IdentityResourceTypeTeam, "role_mapping_test_role_member")
```
Comment (sbose78) [inline authorization/role/repository/role_mapping_blackbox_test.go]: Could you use `uuid.NewV4().String()` to generate the random strings? That will ensure you will never have a name conflict.

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-409-1`

File: authorization/role/repository/role_mapping_blackbox_test.go (hunk 1 above)
Comment (sbryzak) [reply authorization/role/repository/role_mapping_blackbox_test.go]: There isn't actually a name conflict here.

Comment (sbryzak) [reply authorization/role/repository/role_mapping_blackbox_test.go]: I should clarify - at first I thought there _was_ a name conflict, but it turned out that there wasn't. ;)

Comment (sbose78) [reply authorization/role/repository/role_mapping_blackbox_test.go]: so, is this PR only to support removal of the parent resource link?

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-409-2`

**Comment by alexeykazakov** [comment]
[test]

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-409-3`

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-409-5`

**Comment by alexeykazakov** [comment]
[test]
