### PR TITLE
If fragment already present, return it

### LINKED ISSUE #695: fragment part of the `redirect_uri` not managed correctly by the `authorize` endpoint.
## Expected behavior

When calling the `authorize endpoint with the following parameters:
```
https://auth.openshift.io/api/authorize?client_id=740650a2-9c44-4db5-b067-a3d1b2cd2d01&redirect_uri=https%3A%2F%2Fche.openshift.io%2Fdashboard%2F%23%2Ffactories&state=e718826e-c356-45dd-825a-59a4b1f22299&response_mode=fragment&response_type=code&scope=openid
```
(please note that, once decoded, the `redirec_uri` is
`https://che.openshift.io/dashboard/#/factories`),

we would expect the browser to be redirected to the requested `redirecr_uri` followed by the additional fragment parameters corresponding to the OIDC authentication results (code, state, etc ...), just like that:
```
https://che.openshift.io/dashboard/#/factories&code=uss.funn2d7pd-Mk4aj1wcZ7h231Tuk6rQROEdbgYq_W1BA.a59c3250-b5d4-44fc-be8d-50b71b843974.98447a27-40de-450b-a987-1ddc97730839&state=e718826e-c356-45dd-825a-59a4b1f22299
```

## Actual behavior

Instead, the fragment part of the initial `redirect_uri` is __not included__ in the final url the browser is redirected to, as show by the following URL where the browser is really redirected to in previous example above:  
```
https://che.openshift.io/dashboard/#code=uss.funn2d7pd-Mk4aj1wcZ7h231Tuk6rQROEdbgYq_W1BA.a59c3250-b5d4-44fc-be8d-50b71b843974.98447a27-40de-450b-a987-1ddc97730839&state=e718826e-c356-45dd-825a-59a4b1f22299"
```

## Steps to reproduce the problem

Just point the browser to `https://che.openshift.io/dashboard/#/factories`, and see that, after login through `fabric8_auth`, the final page is `https://che.openshift.io/dashboard/#/`

## Specifications

This occurs on the production version of `fabric8_auth`

### PR DESCRIPTION
**Pull request by sbose78**
fixes #695 , https://github.com/redhat-developer/rh-che/issues/839

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-696-1`

**Comment by davidfestal** [comment]
Thanks @sbose78 !

File: login/service.go [hunk 1]
```diff
@@ -362,7 +362,12 @@ func (keycloak *KeycloakOAuthProvider) AuthCodeCallback(ctx *app.CallbackAuthori
 	parameters.Add("state", ctx.State)
 
 	if responseMode != nil && *responseMode == "fragment" {
-		referrerURL.Fragment = parameters.Encode()
+		if referrerURL.Fragment != "" {
+			referrerURL.Fragment = referrerURL.Fragment + "&" + parameters.Encode()
```
Comment (xcoulon) [inline login/service.go]: you could also use `fmt.Sprintf(...)` to concatenate the current fragment and the encoded params

File: login/service_login_blackbox_test.go [hunk 2]
```diff
@@ -188,26 +188,41 @@ func (s *serviceLoginBlackBoxTest) runLoginEndToEnd() {
 func (s *serviceLoginBlackBoxTest) TestOauth2LoginEndToEnd() {
 	s.approved = true
 	s.alreadyLoggedIn = false
-	s.runOauth2LoginEndToEnd()
+	modeFragment := "fragment"
```
Comment (xcoulon) [inline login/service_login_blackbox_test.go]: you could use subtests here :) (seriously, named subtests would give some insight about what you're actually testing)

File: login/service_login_blackbox_test.go [hunk 3]
```diff
@@ -188,26 +188,41 @@ func (s *serviceLoginBlackBoxTest) runLoginEndToEnd() {
...
+	s.alreadyLoggedIn = false
+	s.runOauth2LoginEndToEnd("https://randomurl/with/#fragment", modeQuery)
+
 }
 
 func (s *serviceLoginBlackBoxTest) TestOauth2LoginEndToEndNotApproved() {
 	s.approved = false
 	s.alreadyLoggedIn = false
-	s.runOauth2LoginEndToEnd()
+	modeFragment := "fragment"
```
Comment (xcoulon) [inline login/service_login_blackbox_test.go]: and then, this test could be moved as a subtest above, too

File: login/service_login_blackbox_test.go [hunk 4]
```diff
@@ -268,10 +283,21 @@ func (s *serviceLoginBlackBoxTest) runOauth2LoginEndToEnd() {
 
 	redirectedToURLRef, err = url.Parse(*redirectedTo)
 	require.NoError(s.T(), err)
-	require.Equal(s.T(), redirectURL, redirectedToURLRef.Scheme+"://"+redirectedToURLRef.Host+redirectedToURLRef.Path)
-	require.Equal(s.T(), s.Configuration.GetPublicOauthClientID(), redirectedToURLRef.Query()["api_client"][0])
-	require.Equal(s.T(), state, redirectedToURLRef.Query()["state"][0])
-	require.Equal(s.T(), returnedCode, redirectedToURLRef.Query()["code"][0])
+
```
Comment (xcoulon) [inline login/service_login_blackbox_test.go]: what about splitting this function in 2 parts: above to perform the "business" call, and below in 2 distinct functions to verify the result?

Comment (sbose78) [reply login/service_login_blackbox_test.go]: There are way too many places where we are validating state and code, I tried considering having a function to validate that - but then it might end up being called again and again, to an extent that there it the code might actually not look any clean :)

File: login/service_login_blackbox_test.go (hunk 2 above)
Comment (sbose78) [reply login/service_login_blackbox_test.go]: I agree - but since we are avoiding that paradigm, I avoided it as well :|
